import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/design-components/Header";
import Footer from "@/components/design-components/Footer";
import ButtonGradient from "@/assets/svg/ButtonGradient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Anas Ahmed | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} font-sans ${geistMono.variable} antialiased`}
      >
        <div className="overflow-hidden max-sm:px-4">
          <Header />
          {children}
          <Footer />
        </div>

        <ButtonGradient />
      </body>
    </html>
  );
}
